#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
END_COLOR='\033[0m' # No Color

echo "Checking OS version..."
if [ "$(grep -Ei 'VERSION_ID="10"' /etc/os-release)" ] && [ "$(grep -Ei 'ID=debian' /etc/os-release)" ]; then
  printf "${GREEN}$(cat /etc/os-release)${END_COLOR}\n"
  exit 0
else
  printf "${RED}$(cat /etc/os-release)${END_COLOR}\n"
  exit 1
fi
