#!/usr/bin/env ruby

# NOTE: This must be ran as root!

unless File.exists?('/swapfile')
  `fallocate -l #{ARGV.first} /swapfile`
  `chmod 0600 /swapfile`
  `mkswap /swapfile`
  `swapon /swapfile`
  File.open("/etc/fstab", "a") do |file|
    file.write("/swapfile none swap sw 0 0")
  end
end
