#!/usr/bin/env ruby

YELLOW = "\033[0;33m"
END_COLOR = "\033[0m" # No Color

all_hostnames = ARGV

puts "### Running certbot interactively ###"
puts "#{YELLOW}### When prompted by certbot, select \"No redirect\" so it won't alter the nginx config. ####{END_COLOR}"
puts "#{YELLOW}### This script's nginx config already does that, and certbot would break it. ####{END_COLOR}"
exec "sudo certbot --nginx #{all_hostnames.map { |s| "-d #{s}"}.join(" ")} --agree-tos --email devs@rubyshore.com --manual-public-ip-logging-ok --force-interactive"
